[tools]
golang = "1.22"
shfmt = "3"
golangci-lint = "1.59"
goreleaser = "latest"
"go:gotest.tools/gotestsum" = "v1.12.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"

[tasks.build]
description = "Build a binary for the current platform/architecture"
sources = ["cmd/**/*.go", "internal/**/*.go", "go.mod", "go.sum"]
outputs = ["./bin/wrapper", "./bin/downloader"]
run = "go build -v -trimpath -o ./bin/ ./cmd/..."

[tasks.test]
description = "Run tests"
run = "gotestsum"

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.fmt]
alias = "format"
description = "Format code"
run = [
  "go mod tidy",
  "gofmt -s -w .",
  "goimports -w .",
  "shfmt -w -i 2 -ci -sr .",
]

[tasks.docker-build]
description = "Build a local Docker image"
run = "docker buildx build --build-arg GO_VERSION=$(mise current golang) -t ghcr.io/jaredallard/factorio:local --load ."
